### ISSUE TITLE
Problem running this ionic2-geofence code : Dependency missing for @ionic/cli-plugin-core

### ISSUE THREAD

**Issue by pratibhamantur** [tsubik/ionic2-geofence#10]
Whenever running this code I m getting this error: 
**Dependency missing for @ionic/cli-plugin-core** 
for following system information:
Cordova CLI: 6.5.0
Ionic Framework Version:2.0.1
ios-deploy version: not installed
OS:Windows 7
Node Version: v6.9.4
Xcode Version:Not installed

**Comment by tsubik** [comment]
If you are trying to build for iOS, I clearly see you have message about missing dependencies
```
ios-deploy version: not installed
Xcode Version:Not installed
```
