### ISSUE TITLE
Memory usage causing app to get closed on iOS

### ISSUE THREAD

**Issue by lhammond** [tsubik/ionic2-geofence#2]
In XCode, I see the memory climb until the app is shutdown.

**Comment by numerized** [comment]
Hi There, 

When I launch the app the first time, everything is working, once I shut it down and launch it the second time, it doesn't go through the splash screen.

I have to reboot the phone and then the app restarts well.

I tried to update to Ionic beta 11 and fix the breaking changes, same problem. First load after reboot ok, next loads not ok.

Thanks for demo guys is really promising !

ionic -v
2.0.0-beta.37

cordova -v
6.3.1

**Comment by tsubik** [comment]
I just fixed some problems with splashscreen on iOS here https://github.com/tsubik/ionic2-geofence/commit/30e4b17b73764896c5d880c0658f064f3b9c624c. Maybe that helps.
