### ISSUE TITLE
Errors on first start

### ISSUE THREAD

**Issue by kaynz** [tsubik/ionic2-geofence#3]
Hey,

I just cloned this repository, installied ionic-cli, executed npm install and ionic serve, got this error:

http://pastebin.com/SYq83GNj

**Comment by tsubik** [comment]
Hey @kaynz, thanks for reporting this. It looked like some dependencies had changed and that's why the project was broken. I've added shrinkwrap file and I hope that will prevent this from happening. Anyway, I've also got rid of typescript errors.
