### ISSUE TITLE
update to ionic2 rc1 / latest

### ISSUE THREAD

**Issue by PhilippRath** [tsubik/ionic2-geofence#6]
hi, 
great Projekt would be nice to have a example for the latest ionic2 Version since the Angular part and the ionic2 Part of the framework likely to be stable, there won't be much changes to come.

**Comment by tsubik** [comment]
@rathgeber2 I agree, that should be upgraded. Don't have time for this now, though. Previous updates of beta versions were actually time-consuming, I had to go through the changelog and every and each minor version upgrade guide.

**Comment by tsubik** [comment]
Upgraded in https://github.com/tsubik/ionic2-geofence/commit/33f25258045fdac86c9772810c1a7ceb51c96ed5 :smiley:
