### ISSUE TITLE
Leaflet map not loading

### ISSUE THREAD

**Issue by thomashrabe** [tsubik/ionic2-geofence#7]
Hi Tomasz,

seems you solved the leaflet map not loading issue with the timeout.
I am trying to add Leaflet to my ionic2 app started from the blank template.

I can add the map object, but even when I use the timeout to load the map, only few map tiles will be loaded. 

Using Leaflet 1.0.2 as it comes with npm. Any idea?

**Comment by tsubik** [comment]
I found some time to upgrade to the latest ionic2 version. Got the same problem, it was related to not loaded css files for leaflet. I have no idea how to hook up loading custom css into new ionic build system so I've added leaflet css link directly into [index.html](https://github.com/tsubik/ionic2-geofence/blob/master/src/index.html#L16).
