### ISSUE TITLE
Failed on npm install

### ISSUE THREAD

**Issue by aharonamir** [tsubik/ionic2-geofence#8]
Not working on npm version 4.0.3
Got message " Cannot read property 'debug' of undefined"
problem was in /usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js
After downgrading npm to 3.10.9 problem solved

**Comment by tsubik** [comment]
Looks like it's not an issue with this code but some dependent plugin. Didn't know there is npm version 4 already, but I will have to maybe add yarn here as it's more deterministic.
